apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/kubeintent.io_appintents.yaml
  - bases/kubeintent.io_runtimeprofiles.yaml
  - bases/kubeintent.io_namespaceintents.yaml
  - bases/kubeintent.io_driftexceptions.yaml
